// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFprf4RqaEUH5equnJaf1CErIapRcFWcw',
    appId: '1:794746531374:android:73771e8741ddc80814b9bf',
    messagingSenderId: '794746531374',
    projectId: 'flutter-uber-clone-443e8',
    databaseURL: 'https://flutter-uber-clone-443e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-443e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyWEpuT8rn58TflZzu1b8bQcn488cCyI',
    appId: '1:794746531374:ios:72ea30273862ec1c14b9bf',
    messagingSenderId: '794746531374',
    projectId: 'flutter-uber-clone-443e8',
    databaseURL: 'https://flutter-uber-clone-443e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-uber-clone-443e8.appspot.com',
    iosBundleId: 'com.example.drriver',
  );
}
